Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.image as mpimg

grace = mpimg.imread('../Assets/grace_hopper.jpg')
print(grace.shape)
print(type(grace))


jean = mpimg.imread('../Assets/jean_sammet.jpg')
print(type(jean))

cirs = mpimg.imread('../Assets/cirs_slice.png')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[23], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mimage[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmpimg[39;00m
[0;32m----> 3[0m grace [38;5;241m=[39m [43mmpimg[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m../Assets/grace_hopper.jpg[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      4[0m [38;5;28mprint[39m(grace[38;5;241m.[39mshape)
[1;32m      5[0m [38;5;28mprint[39m([38;5;28mtype[39m(grace))

File [0;32m/opt/miniconda3/lib/python3.9/site-packages/matplotlib/image.py:1560[0m, in [0;36mimread[0;34m(fname, format)[0m
[1;32m   1558[0m                 response [38;5;241m=[39m io[38;5;241m.[39mBytesIO(response[38;5;241m.[39mread())
[1;32m   1559[0m             [38;5;28;01mreturn[39;00m imread(response, [38;5;28mformat[39m[38;5;241m=[39mext)
[0;32m-> 1560[0m [38;5;28;01mwith[39;00m [43mimg_open[49m[43m([49m[43mfname[49m[43m)[49m [38;5;28;01mas[39;00m image:
[1;32m   1561[0m     [38;5;28;01mreturn[39;00m (_pil_png_to_float_array(image)
[1;32m   1562[0m             [38;5;28;01mif[39;00m [38;5;28misinstance[39m(image, PIL[38;5;241m.[39mPngImagePlugin[38;5;241m.[39mPngImageFile) [38;5;28;01melse[39;00m
[1;32m   1563[0m             pil_to_array(image))

File [0;32m/opt/miniconda3/lib/python3.9/site-packages/PIL/Image.py:3227[0m, in [0;36mopen[0;34m(fp, mode, formats)[0m
[1;32m   3224[0m     filename [38;5;241m=[39m fp
[1;32m   3226[0m [38;5;28;01mif[39;00m filename:
[0;32m-> 3227[0m     fp [38;5;241m=[39m [43mbuiltins[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m   3228[0m     exclusive_fp [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m   3230[0m [38;5;28;01mtry[39;00m:

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../Assets/grace_hopper.jpg'
FileNotFoundError: [Errno 2] No such file or directory: '../Assets/grace_hopper.jpg'

