Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
DCM = pydicom.dcmread(r'../Assets/CT/IM-0001-0200-0001.dcm')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m DCM [38;5;241m=[39m [43mpydicom[49m[38;5;241;43m.[39;49m[43mdcmread[49m[43m([49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[38;5;124;43m../Assets/CT/IM-0001-0200-0001.dcm[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/opt/miniconda3/lib/python3.9/site-packages/pydicom/filereader.py:993[0m, in [0;36mdcmread[0;34m(fp, defer_size, stop_before_pixels, force, specific_tags)[0m
[1;32m    991[0m     caller_owns_file [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m    992[0m     logger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mReading file [39m[38;5;124m'[39m[38;5;132;01m{0}[39;00m[38;5;124m'[39m[38;5;124m"[39m[38;5;241m.[39mformat(fp))
[0;32m--> 993[0m     fp [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[43mfp[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    994[0m [38;5;28;01melif[39;00m fp [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(fp, [38;5;124m"[39m[38;5;124mread[39m[38;5;124m"[39m) [38;5;129;01mor[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(fp, [38;5;124m"[39m[38;5;124mseek[39m[38;5;124m"[39m):
[1;32m    995[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124m"[39m[38;5;124mdcmread: Expected a file path or a file-like, [39m[38;5;124m"[39m
[1;32m    996[0m                     [38;5;124m"[39m[38;5;124mbut got [39m[38;5;124m"[39m [38;5;241m+[39m [38;5;28mtype[39m(fp)[38;5;241m.[39m[38;5;18m__name__[39m)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../Assets/CT/IM-0001-0200-0001.dcm'
FileNotFoundError: [Errno 2] No such file or directory: '../Assets/CT/IM-0001-0200-0001.dcm'

